import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'fr_FR': {
          'login_title': 'CONNEXION',
          'remember': 'Se rappeler de moi',
          'forgot_password': 'Mot de passe oublié?',
          'phone_number': 'Numéro de téléphone',
          'password': 'Mot de passe',
          'new_password':'Entrer nouveau mot de passe',
          'confirm_new_password':'Confirmer nouveau mot de passe',
          'log_in': 'SE CONNECTER',
          'have_not_account': 'Vous n\'avez pas encore de compte ?',
          'sign_up': 'Inscrivez-vous',
          'register': 'INSCRIPTION',
          'full_name': 'Nom et prénoms',
          'email_adress': 'Entrer votre e-mail',
          'select_city': 'Sélectionner votre pays',
          'sign_up_register': 'S\'INSCRIRE',
          'already_account': 'Dèjà un compte ?',
          'login_in_register': 'Connectez-vous',
          'enter_the_code': 'Entrez le code reçu',
          'otp_message':
              'Veuillez saisir le code reçu par e-mail afin de terminer votre inscription',
          'dont_receive_code': "Vous n'avez pas reçu de code ?",
          'try_again': "Rééssayer",
          'forg_pass': "MOT DE PASSE OUBLIE",
          'forg_pass_message':
              "Mot de passe oublié ? Entrez votre email pour recevoir un code de réinitialisation.",
          'confirm': 'CONFIRMER',
          'validate': 'valider',
          'sejour_home_text':
              'Envie d’un séjour de qualité sans soucis de déplacement vous êtes a la bonne porte',
          'location': "Location",
          'discover': "Découverte",
          'stay': "Séjour",
          'louer_vehicule': "Louez un véhicule avec chauffeur ",
          'apartir_de': 'A partir de',
          'tourism': 'Envie de faire du tourisme',
          'sejourn': 'Envie de séjourner',
          'find_vehicle': 'Rechercher un vehicule',
          'vehicule_quality':
              'Nous mettons des chauffeurs et vehicules de qualité à votre disposition',
          'passengers': 'passagers',
          'valise': 'valise(s)',
          'siege_enfant': 'siège enfant',
          'air-conditioning': 'climatisation',
          'economy': 'Economie',
          'business': 'Business',
          'chargers_on_hand': 'Chargeur à porter de main',
          'place_of_care': 'Lieu de prise en charge',
          'recent_choice': 'Choix récent',
          'place_of_return': 'Lieu de restitution',
          'location_period': 'Période de location',
          'edit': 'Modifier',
          'driver': 'Chauffeur',
          'change': 'Changer',
          'rating': 'Note',
          'Bon_a_savoir': 'Bon a savoir',
          'frais_carburant': 'Les frais de carburants sont à vos charges.',
          'accompt': 'Vous payez un acompte de 10% non remboursable',
          'p_payment': 'Passer au paiement',
          'invoice_sommary': 'Résumé de la facture',
          'class': 'Classe',
          'accomp_requis': 'Un acompte de 10% est requis',
          'remboursment': 'Aucun remboursement n’est effectué après paiement',
          'cout_journalier': 'Coût journalier',
          'cout_total': 'Coût total',
          'invoic_payment': 'Règlement de la facture',
          'total_payment': 'Paiement total',
          'regler_facture': 'Régler la facture',
          'Find_a_motel': 'Rechercher un motel',
          'sejour_memorable':
              'Voulez-vous passer un séjour mémorable ? vous êtes à la bonne porte',
          'domestic': 'ménage',
          'petit_dej': 'petit dej',
          'lit': 'lit(s)',
          'salle_bain': 'salle(s) de bain',
          'clim': 'climatiseur(s)',
          'details': 'Détails',
          'vue_balcon': 'vue sur balcon',
          'jour': 'jour',
          'emplacement': 'Emplacement',
          'period_reservation': 'Période de réservation',
          'reserv_now': 'Réserver maintenant',
          'prise_charge': 'Prise en charge',
          'enregister': 'Enregistrer',
          'chambre': 'Chambre',
          'localisation': 'Localisation',
          'success_payment': 'Paiement effectué avec succès',
          'Find_a_site': 'Rechercher un site',
          'uniqu_experience':
              'Plongez dans une expérience unique au cœur de la Cote d’Ivoire',
          'visit_guide': 'Visite guidée a partir de',
          'history': 'Historique',
          'pour': 'pour',
          'point_rassemblement': 'Point de rassemblement',
          'visit': 'Visite',
          'visit_period': 'Période de visite',
          'my_profil': 'Mon profil',
          'contact_support': 'Contactez le support',
          'question': 'Question',
          'response': 'Reponse',
          'q_location_service':
              "Proposez-vous des services de location à l'international ?",
          'r_location_service':
              "Nous ne proposons pas actuellement de services de location à l'international. Cependant, nous offrons une large gamme de véhicules à la location au niveau national et nous restons à votre disposition pour vous accompagner dans vos besoins de mobilité. Si vous avez des questions spécifiques ou si vous souhaitez plus d'informations sur nos offres, n'hésitez pas à nous contacter.",
          'q_location_driver':
              "Proposez-vous la location de véhicules sans chauffeur ? Si oui, quelles en sont les conditions ?",
          'r_location_driver':
              "Oui, nous proposons la location de véhicules sans chauffeur. Pour louer un véhicule sans chauffeur, certaines conditions s'appliquent :",
        },
        'en_US': {
          'r_location_driver':
              "Yes, we offer vehicle rental without a driver. To rent a vehicle without a driver, certain conditions apply:",
          'q_location_driver':
              "Do you offer driverless car rental? If so, what are the conditions?",
          'r_location_service':
              "We do not currently offer international rental services. However, we do offer a wide range of vehicles for rental nationwide, and we remain at your disposal to assist you with your mobility needs. If you have any specific questions or would like more information about our offers, please do not hesitate to contact us.",
          'q_location_service': "Do you offer international rental services?",
          'question': 'Question',
          'response': 'Response',
          'contact_support': 'Contact support',
          'my_profil': 'My profile',
          'visit_period': 'Visit period',
          'new_password':'Enter your new password',
          'confirm_new_password':'Confirm your new password',
          'visit': 'Visit',
          'point_rassemblement': 'Meeting point',
          'pour': 'For',
          'history': 'History',
          'visit_guide': 'Guided tour from',
          'uniqu_experience':
              'Immerse yourself in a unique experience in the heart of the Ivory Coast',
          'Find_a_site': 'Find a site',
          'success_payment': 'Successful payment',
          'localisation': 'Location',
          'chambre': 'Room',
          'enregister': 'Save',
          'prise_charge': 'Support',
          'reserv_now': 'Book now',
          'period_reservation': 'Booking period',
          'emplacement': 'Location',
          'jour': 'day',
          'vue_balcon': 'balcony view',
          'details': 'Details',
          'clim': 'air conditioner',
          'salle_bain': 'bathrooms',
          'lit': 'Bed',
          'petit_dej': 'breakfast',
          'domestic': 'domestic',
          'sejour_memorable':
              "Looking for a memorable stay? You've come to the right place!",
          'Find_a_motel': 'Find a motel',
          'regler_facture': 'Pay the invoice',
          'total_payment': 'Total payment',
          'invoic_payment': 'Invoice payment',
          'cout_total': 'Total cost',
          'cout_journalier': 'Daily cost',
          'remboursment': 'No refunds will be made after payment',
          'accomp_requis': 'A 10% deposit is required',
          'class': 'Class',
          'invoice_sommary': 'Invoice summary',
          'p_payment': 'Proceed to payment',
          'accompt': 'You pay a non-refundable 10% deposit',
          'frais_carburant': 'Fuel costs are at your expense',
          'Bon_a_savoir': 'Good to Know',
          'rating': 'Rating',
          'change': 'Change',
          'driver': 'Driver',
          'edit': 'Edit',
          'location_period': 'Rental period',
          'place_of_return': 'Place of return',
          'recent_choice': 'Recent choice',
          'place_of_care': 'Place of care',
          'chargers_on_hand': 'Chargers on hand',
          'business': 'Business',
          'economy': 'Economy',
          'air-conditioning': 'air-conditioning',
          'siege_enfant': 'Child seat',
          'valise': 'Suitcase',
          'passengers': 'Passengers',
          'vehicule_quality':
              'We put quality drivers and vehicles at your disposal',
          'find_vehicle': 'Find a vehicle',
          'sejourn': 'Want to stay',
          'tourism': 'A taste for tourism',
          'apartir_de': 'From',
          'louer_vehicule': "Rent a car with driver",
          'location': "Location",
          'discover': "Discover",
          'stay': "Stay",
          'sejour_home_text':
              "If you're looking for a quality stay with no travel worries, you've come to the right place.",
          'validate': 'Validate',
          'confirm': 'Confirm',
          'forg_pass_message':
              "Forgot your password? Enter your email to receive a reset code.",
          'forg_pass': "FORGOT PASSWORD",
          'try_again': "Try again",
          'login_title': 'LOGIN',
          'remember': 'Remember me',
          'forgot_password': 'Forgot your password?',
          'phone_number': 'Enter your phone number',
          'password': 'Enter your password',
          'log_in': 'Sign in',
          'have_not_account': 'Don\'t have an account?',
          'sign_up': 'Sign up',
          'register': 'REGISTER',
          'full_name': 'Full name',
          'email_adress': 'Enter your e-mail address',
          'select_city': 'Select your country',
          'sign_up_register': 'SIGN UP',
          'already_account': 'Already have an account?',
          'login_in_register': 'Log in',
          'enter_the_code': 'Enter the code',
          'otp_message':
              'A verification code has been sent to your phone number. Please enter the code below to continue.',
          'dont_receive_code': "You haven't received a code?",
        },
      };
}
